### ISSUE TITLE
generateIntelliJTask does not create tasks in IntelliJ 2016.1.1

### ISSUE THREAD

**Issue by dentych** [Qixalite/SpongeStart#8] opened 2016-05-03 21:34 UTC
I ran setupServer which completed successfully.
The external library "start" was present in External libraries, the run folder was created and had both vanilla and forge. The only thing missing was the run configurations. I had to manually create them.

**Comment by kinggoesgaming** [comment] 2016-05-04 02:18
Can confirm as i helped @dentych to get going for now

**Comment by thomas15v** [comment] 2016-05-07 13:33
Did it gave any crashlog? I tested it on windows and it worked fine for me.

**Comment by dentych** [comment] 2016-05-08 21:20
There was no crash log. The gradle build steps completed successfully, without warnings or errors. When I went to the "Run configurations" setting, nothing had been created.

**Comment by thomas15v** [comment] 2016-05-19 06:58
![naamloos](https://cloud.githubusercontent.com/assets/2163941/15385132/c82bfe36-1d9f-11e6-82ab-ec4b4df90dcf.png)
Tested it on IDEA 2016.1.2 as well. I can't figure out why it doesn't work for you.

**Comment by dentych** [comment] 2016-05-19 07:09
That is odd. I will try to update IDEA to 2016.1.2 and give it shot again.. Thanks for looking into it, though :)

**Comment by thomas15v** [comment] 2016-05-25 08:29
@dentych Did you figured it out?

**Comment by dentych** [comment] 2016-05-25 11:15
Sorry, I did not. I installed IDEA 2016.1.2 yesterday to try it out, but never got around to actually test it, because something came in the way. I'll do it when I get home - I put it in my calendar now :smile:

**Comment by dentych** [comment] 2016-05-26 18:27
Hey there. So I tried making a new project, copy the exact build.gradle config found in README.md, and then executed the "setupVanilla" gradle task.. This is the outcome.

![image](https://cloud.githubusercontent.com/assets/2256372/15585569/341165d8-2380-11e6-9e5c-32541bbd7aa4.png)

**Comment by thomas15v** [comment] 2016-05-27 08:53
And in the folder ```.idea/runConfigurations```? Did it generated any files?

**Comment by dentych** [comment] 2016-05-29 23:47
Nope. Folder doesn't exist.

**Comment by FerusGrim** [comment] 2016-06-09 07:41
@dentych Could you do me a favor and test something?

- Delete the projects files - start from fresh (or just create a new project for the test)
- Create a project using IntelliJ.
- As soon as the initial building finishes (and you configure GradleStart), close IntelliJ.
- Run the commands manually from a CLI.
- Open IntelliJ.

After that, are the configurations now visible? Can you run them?

**Comment by thomas15v** [comment] 2016-06-26 15:51
My best guess is that it's a permission problem on .idea. I will close this because I can't reproduce.

**Closed by thomas15v** 2016-06-26 15:51 UTC
Labels: bug

**Comment by dentych** [comment] 2016-07-14 19:02
Just to let you know, it works when it's run from CLI. I didn't start from fresh, I simply tried to run ./gradlew generateIntelliJTask while IntelliJ was closed. When I opened up the project in IntelliJ, the two run targets were there :smile:
